### ISSUE TITLE
Feature request: Reading mode

### ISSUE THREAD

**Issue by adamryczkowski** [fopeczek/LoudReadingSkill#2]
The input will be a text file that the algorithm will cut into sentences, and present one-by-one to the student. 

The algorithm will proceed to the next sentence from the book only after a student passed reading the old one well enough (with a adjustable threshold).

**Comment by fopeczek** [comment]
Implemented, but there is no adjustable threshold, work in progress

**Comment by fopeczek** [comment]
Implemented adjustable threshold (correct_min_accuracy and correct_min_speed)
